# container image catalog
containerimages:
  # golang
  - image: quay.io/cidverse/build-go:1.19.3
    provides:
      - binary: go
        version: 1.19.3
    cache:
      - id: go-pkg
        dir: /go/pkg
  # golangci-lint
  - image: docker.io/golangci/golangci-lint:v1.46.2-alpine
    provides:
      - binary: golangci-lint
        version: 1.46.2
  - image: docker.io/golangci/golangci-lint:v1.46.1-alpine
    provides:
      - binary: golangci-lint
        version: 1.46.1
  - image: docker.io/golangci/golangci-lint:v1.46.0-alpine
    provides:
      - binary: golangci-lint
        version: 1.46.0
  - image: docker.io/golangci/golangci-lint:v1.45.2-alpine
    provides:
      - binary: golangci-lint
        version: 1.45.2
  # java
  - image: quay.io/cidverse/base-coretto-17:17.0.4.9.1
    provides:
      - binary: java
        version: 17.0.4
    cache:
      - id: java-gradle
        dir: /root/.gradle
      - id: java-maven
        dir: /root/.m2
  - image: quay.io/cidverse/base-coretto-11:11.0.16.9.1
    provides:
      - binary: java
        version: 11.0.16
    cache:
      - id: java-gradle
        dir: /root/.gradle
      - id: java-maven
        dir: /root/.m2
  - image: docker.io/eclipse-temurin:8u322-b06-jdk
    provides:
      - binary: java
        version: 8.0.0
    cache:
      - id: java-gradle
        dir: /root/.gradle
      - id: java-maven
        dir: /root/.m2
  # node (npm, yarn, npx)
  - image: node:18.8.0-slim
    provides:
      - binary: node
        version: 18.8.0
      - binary: yarn
        version: 1.22.18
      - binary: npx
        version: 18.8.0
    cache:
      - id: node-npm
        dir: /root/.npm
      - id: node-yarn-cache-v6
        dir: /usr/local/share/.cache/yarn/v6
      - id: node-yarn-config
        dir: /root/.config/yarn
  # helm
  - image: quay.io/cidverse/helm:3.10.1
    provides:
      - binary: helm
        version: 3.10.1
    cache:
      - id: helm-config
        dir: /app/.config/helm
      - id: helm-cache
        dir: /app/.cache/helm/cache
      - id: helm-plugins
        dir: /app/.cache/helm/plugins
      - id: helm-repository
        dir: /app/.cache/helm/repository
  # upx
  - image: quay.io/cidverse/upx:4.0.1
    provides:
      - binary: upx
        version: 4.0.1
  # gitguardian ggshield
  - image: quay.io/cidverse/ggshield:1.13.6
    provides:
      - binary: ggshield
        version: 1.13.6
  # sonarqube
  - image: quay.io/cidverse/sonarscannercli:4.7.0.2747
    provides:
      - binary: sonar-scanner
        version: 4.7.0
    cache:
      - id: sonarscanner-cache
        dir: /opt/sonar-scanner/.sonar
  # trivy security scanner
  - image: docker.io/aquasec/trivy:0.32.1
    provides:
      - binary: trivy
        version: 0.32.1
    cache:
      - id: trivy-cache
        dir: /root/.cache/trivy
  # shellcheck
  - image: quay.io/cidverse/shellcheck:0.8.0
    provides:
      - binary: shellcheck
        version: 0.8.0
  # githubcli - gh
  - image: quay.io/cidverse/githubcli:2.18.0
    provides:
      - binary: gh
        version: 2.18.0
  # twitch
  - image: quay.io/cidverse/twitchcli:1.1.8
    provides:
      - binary: twitch
        version: 1.1.8
    cache:
      - id: twitchcli-config
        dir: /root/.twitch-cli
  # fossa
  - image: quay.io/cidverse/fossacli:3.4.11
    provides:
      - binary: fossa
        version: 3.4.11
  # hadolint
  - image: quay.io/cidverse/hadolint:2.10.0
    provides:
      - binary: hadolint
        version: 2.10.0
  # buildah
  - image: quay.io/cidverse/buildah:1.28.2
    provides:
      - binary: buildah
        version: 1.28.2
      - binary: buildah-script
        version: 1.28.2
    security:
      privileged: true
      #capabilities:
      #  - CAP_SETGID
      #  - CAP_SETUID
    cache:
      - id: libcontainers-storage
        dir: /var/lib/containers/storage
      - id: container-auth
        dir: /app/.auth
  # gitleaks
  - image: quay.io/cidverse/gitleaks:8.15.1
    provides:
      - binary: gitleaks
        version: 8.15.1
  # syft
  - image: quay.io/cidverse/syft:0.62.0
    provides:
      - binary: syft
        version: 0.62.0
  # grype
  - image: quay.io/cidverse/grype:0.53.0
    provides:
      - binary: grype
        version: 0.53.0
    cache:
      - id: grype-cache
        dir: /app/.cache/grype
  # cosign
  - image: quay.io/cidverse/cosign:1.13.1
    provides:
      - binary: cosign
        version: 1.13.1
  # rekor
  - image: quay.io/cidverse/rekor:1.0.0
    provides:
      - binary: rekor
        version: 1.0.0
  # hugo
  - image: quay.io/cidverse/hugo:0.104.3
    provides:
      - binary: hugo
        version: 0.104.3
  # rke
  - image: quay.io/cidverse/rke:1.3.15
    provides:
      - binary: rke
        version: 1.3.15
  - image: quay.io/cidverse/rke2:1.25.3
    provides:
      - binary: rke2
        version: 1.25.3
  # reposync
  - image: quay.io/cidverse/reposync:0.2.0
    provides:
      - binary: reposync
        version: 0.2.0
  # techdocs-cli
  - image: quay.io/cidverse/techdocscli:1.2.2
    provides:
      - binary: techdocs-cli
        version: 1.2.2
  # mkdocs
  - image: quay.io/cidverse/mkdocs:1.4.2
    provides:
      - binary: mkdocs
        version: 1.4.2
  # pipenv
  - image: quay.io/cidverse/pipenv:2022.11.30
    provides:
      - binary: pipenv
        version: 2022.11.30
    cache:
      - id: pipenv-virtualenvs
        dir: /app/.local/share/virtualenvs
      - id: pipenv-cache
        dir: /app/.cache/pipenv
  # poetry
  - image: quay.io/cidverse/poetry:1.2.2
    provides:
      - binary: poetry
        version: 1.2.2
    cache:
      - id: poetry-cache
        dir: /app/.cache
  # native-image
  - image: quay.io/cidverse/native-image:22.3.0
    provides:
      - binary: native-image
        version: 22.3.0
