# local tools
localtools:
  # docker
  - binary: ["docker"]
    lookup:
      - key: PATH
        version: 0.0.0
  # podman
  - binary: ["podman"]
    lookup:
      - key: PATH
        version: 0.0.0
