# workflow name
name: CI

# workflow triggers
on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".editorconfig"

jobs:
  # build
  build:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: cidverse/ghact-cid-setup@main
        name: CID Setup
      # project checkout
      - uses: actions/checkout@v2
        name: Repository Checkout
        with:
          fetch-depth: 0
      # print execution plan
      - name: CI Execution Plan
        run: |
          cid info
      # build
      - name: Build
        run: |
          cid stage build
      - name: Test
        run: |
          cid stage test
      - name: Packaging
        run: |
          cid stage package
      - name: Static Application Security Testing
        run: |
          cid stage sast
